-- DM8 初始化脚本（简化版，一次性执行）
-- 如需重复执行，请先手动删除已有对象

CREATE TABLE T_LK_MONITOR_STREAM (
  ID VARCHAR2(128) PRIMARY KEY,
  URL VARCHAR2(2048) NOT NULL,
  STATUS VARCHAR2(32) NOT NULL,
  NODE_ID VARCHAR2(128) NOT NULL,
  OUTPUT_DIR VARCHAR2(1024) NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE T_LK_MONITOR_RECORD_FILE (
  ID BIGINT PRIMARY KEY,
  STREAM_ID VARCHAR2(128) NOT NULL,
  FILE_PATH VARCHAR2(2048) NOT NULL,
  START_TIME TIMESTAMP NOT NULL,
  END_TIME TIMESTAMP NOT NULL,
  SIZE BIGINT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_RECORD_FILE_STREAM FOREIGN KEY (STREAM_ID) REFERENCES T_LK_MONITOR_STREAM(ID),
  CONSTRAINT UQ_STREAM_FILE UNIQUE (STREAM_ID, FILE_PATH)
);

CREATE INDEX IDX_RECORD_FILE_STREAM_ID ON T_LK_MONITOR_RECORD_FILE(STREAM_ID);
